Vagrant.configure("2") do |config|
  config.vm.define :debX do |deb|
    deb.vm.hostname = 'debX'
    deb.vm.box = "debian/stretch64"
    deb.vm.box_check_update = false
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "vagrant.yml"
  end
end 

# vi: set ft=ruby :
